services:
  backend:
    build:
      context: ./server
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DEBUG=True
      - OLLAMA_HOST=host.docker.internal:11434
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
    restart: unless-stopped
